# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bff06857045592ada1c6557a574e82a29de2a67815644201228a4e1e93608e4481e81245f49b710b7775f907d187a1251ab50ec0c5831c623e3fc76ac114148

test:
  secret_key_base: 71c298a1d0856be5e538ed80a715858f6da3aee3dd25754d8da1f3544bd7dfab83912d09c253d030b7cf595c27fe82096268befb1a14c31b458241371e79f806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
